### PR TITLE
Support Go to Definition for `include`, `import` etc

### PR DESCRIPTION
**Pull request by moetelo**

### CODE REVIEW

**Comment by Shifu462** [comment]
Merge https://github.com/kaermorchen/twig-language-server/pull/28 first.

**Comment by kaermorchen** [comment]
I think I can't merge this PR. 

Some projects have a few folders with templates and `Go to Definition` will not work correctly

**Comment by aszenz** [comment]
> Some projects have a few folders with templates and `Go to Definition` will not work correctly

We also have multiple folders but they are all in the root directory of the project like

```
project
 -> templates
 -> templates
```

**Comment by moetelo** [comment]
@kaermorchen @aszenz

Is it ok if I use this command to get configuration for "twig.paths" and "twig.default_path"?
```bash
bin/console debug:config twig --format json
```

For Symfony projects with php console, it would work correctly. Otherwise, I have to write code for collecting configuration from yaml + xml + php since [Symfony allows to provide configuration in all three formats](https://symfony.com/doc/current/reference/configuration/twig.html#paths).

**Comment by aszenz** [comment]
> @kaermorchen @aszenz
> 
> Is it ok if I use this command to get configuration for "twig.paths" and "twig.default_path"?
> 
> ```shell
> bin/console debug:config twig --format json
> ```
> 
> For Symfony projects with php console, it would work correctly. Otherwise, I have to write code for collecting configuration from yaml + xml + php since [Symfony allows to provide configuration in all three formats](https://symfony.com/doc/current/reference/configuration/twig.html#paths).

Seems like a good approach

**Comment by moetelo** [comment]
I've pushed a commit that uses `bin/console debug:config twig --format json` to resolve `paths`. The commit includes the mechanism of resolving Docker volume bindings relative to the user's file system if the command starts with `docker compose`.

Please see if this works in your case. @aszenz

-----

Also, this is my last PR here since I've moved far with [my fork of this extension](https://marketplace.visualstudio.com/items?itemName=moetelo.twiggy). The development of both is burdensome for me since with this repository I can't iterate fast, and maintaining all of the inconsistencies between codebases is also problematic.

You are very welcome to cherry-pick and fine-tune any of the features from my fork. @kaermorchen

**Comment by kaermorchen** [comment]
@moetelo Thanks for your contribution

**Pull request merged**
